spring:
  application:
    name: weatherApp

openWeather:
  api:
    key: ${OPEN_WEATHER_API_KEY}
    baseUrl: https://api.openweathermap.org/data/2.5

cache:
  names:
    weather-summaries: weatherSummary
